# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SpinBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InputForm(object):
    def setupUi(self, InputForm):
        InputForm.setObjectName("InputForm")
        InputForm.resize(261, 416)
        self.Cmd_Dial = QtWidgets.QDial(InputForm)
        self.Cmd_Dial.setGeometry(QtCore.QRect(70, 80, 121, 171))
        self.Cmd_Dial.setToolTip("")
        self.Cmd_Dial.setObjectName("Cmd_Dial")
        self.Cmd_Accept = QtWidgets.QPushButton(InputForm)
        self.Cmd_Accept.setGeometry(QtCore.QRect(90, 330, 75, 23))
        self.Cmd_Accept.setObjectName("Cmd_Accept")
        self.spinBox = QtWidgets.QSpinBox(InputForm)
        self.spinBox.setGeometry(QtCore.QRect(80, 270, 101, 22))
        self.spinBox.setMaximum(500)
        self.spinBox.setObjectName("spinBox")
        self.groupBox = QtWidgets.QGroupBox(InputForm)
        self.groupBox.setGeometry(QtCore.QRect(40, 20, 181, 371))
        self.groupBox.setObjectName("groupBox")
        self.groupBox.raise_()
        self.Cmd_Dial.raise_()
        self.Cmd_Accept.raise_()
        self.spinBox.raise_()

        self.retranslateUi(InputForm)
        
        QtCore.QMetaObject.connectSlotsByName(InputForm)

    def retranslateUi(self, InputForm):
        _translate = QtCore.QCoreApplication.translate
        InputForm.setWindowTitle(_translate("InputForm", "Pilot"))
        self.Cmd_Accept.setText(_translate("InputForm", "OK"))
        
        self.groupBox.setTitle(_translate("InputForm", "Pilot"))
        
       
